// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Comment = { id: string, lettering_id: string, content: string, created_at: string, };
