// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Comment = { id: string, lettering_id: string, content: string, user_id: string | null, commenter_name: string | null, status: string, moderation_score: number, moderation_flags: Array<string>, auto_flagged: boolean, needs_review: boolean, review_priority: number, moderated_at: string | null, moderated_by: string | null, moderation_reason: string | null, created_at: string, updated_at: string, };
