// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Contributor = { tag: string, uploads_count: number, likes_received: number, joined_at: string, };
