// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageMetadata = { style: string | null, script: string | null, confidence: number | null, color_palette: Array<string> | null, };
