// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coordinates } from "./Coordinates";
import type { ImageMetadata } from "./ImageMetadata";
import type { LetteringStatus } from "./LetteringStatus";
import type { ThumbnailUrls } from "./ThumbnailUrls";

export type Lettering = { id: string, city_id: string, contributor_tag: string, image_url: string, thumbnail_urls: ThumbnailUrls, location: Coordinates, pin_code: string, detected_text: string | null, ml_metadata: ImageMetadata | null, description: string | null, is_lettering: boolean, status: LetteringStatus, likes_count: number, comments_count: number, image_hash: string | null, report_count: number, report_reasons: Array<string>, cultural_context: string | null, created_at: string, updated_at: string, };
