// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Lettering } from "./Lettering";

export type PaginatedResponse = { letterings: Array<Lettering>, total: bigint, limit: bigint, offset: bigint, };
